import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import AntdConfigProvider from '@/components/context/AntdConfigProvider'
import { AppConfigProvider } from '@/components/context/AppConfigProvider'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang="en">
            <body className={'antialiased'}>
                <AntdRegistry>
                    <NextIntlClientProvider>
                        <AppConfigProvider>
                            <AntdConfigProvider>{children}</AntdConfigProvider>
                        </AppConfigProvider>
                    </NextIntlClientProvider>
                </AntdRegistry>
            </body>
        </html>
    )
}

export default RootLayout
