import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { AppConfigProvider } from '@/components/context/AppConfigProvider'
import './globals.css'
import { ComponentProvider } from '@/components/context/ComponentProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang="en">
            <body>
                <AntdRegistry>
                    <ComponentProvider>
                        <NextIntlClientProvider>
                            <AppConfigProvider>{children}</AppConfigProvider>
                        </NextIntlClientProvider>
                    </ComponentProvider>
                </AntdRegistry>
            </body>
        </html>
    )
}

export default RootLayout
