import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { ThemeProvider } from '~/shared/context/theme-provider'
import './globals.css'
import { AuthProvider } from '~/shared/context/auth-provider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

const RootLayout = async ({
    children
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang="en">
            <body>
                <ThemeProvider>
                    <NextIntlClientProvider>
                        <AuthProvider>
                            {children} {/* Will render your page */}
                        </AuthProvider>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}

export default RootLayout
